### ISSUE TITLE
Why are you using 50 for cycle time? Why not 20?

### ISSUE THREAD

**Issue by joepuzzo** [CommonplaceRobotics/CANV2ProtocolDemoClient#1]
On this line https://github.com/CommonplaceRobotics/CANV2ProtocolDemoClient/blob/master/CANV2ProtocolDemoClient/RobotControlLoop.cs#L16

It states a cycleTime of 20hz so I would expect that value to be 20 not 50. I may be misunderstanding something here but is this wrong?

**Comment by cpr-jar** [comment]
In the code it is refered to as cycleTime with expects an time intervall so 50 means milliseconds in this case. The comment ist refering to the frequency 20hz which results from the 50ms
